[package]
name = "cargo-axiom"
version = "0.1.1"
edition = "2021"
description = "A Cargo subcommand for the Axiom Proving API"
authors = ["Axiom Team"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
cargo_metadata = "0.18"
dialoguer = { version = "0.10.4" }
dirs = "5.0.1"
reqwest = { version = "0.11", features = ["json", "blocking", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = { version = "0.4" }
flate2 = "1.0"
tokio = { version = "1", features = ["full"] }
walkdir = "2.3"
eyre = "0.6.12"
hex = "0.4.3"
cargo-openvm = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.2.1-rc.0", default-features = false }
openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.2.1-rc.0", default-features = false }
openvm-build = { git = "https://github.com/openvm-org/openvm.git", tag = "v1.2.1-rc.0", default-features = false }
comfy-table = "6.1.4"
dotenv = "0.15.0"
rustc_version = "0.4.0"

[build-dependencies]
cargo_metadata = "0.18"
