[package]
name = "cargo-axiom"
version = "0.1.0"
edition = "2021"
description = "A Cargo subcommand for Axiom operations"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
anyhow = "1.0"
