[package]
name = "cargo-axiom"
version = "0.1.0"
edition = "2021"
description = "A Cargo subcommand for Axiom operations"
authors = ["Your Name <your.email@example.com>"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
dialoguer = "0.10.4"
dirs = "5.0.1"
reqwest = { version = "0.11", features = ["json", "blocking", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
flate2 = "1.0"
tokio = { version = "1", features = ["full"] }
walkdir = "2.3"
eyre = "0.6.12"
hex = "0.4.3"
cargo-openvm = { git = "https://github.com/openvm-org/openvm.git", rev = "f41640c37bc5468a0775a38098053fe37ea3538a" }
openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", rev = "f41640c37bc5468a0775a38098053fe37ea3538a" }
comfy-table = "6.1.4"