[package]
name = "cargo-axiom"
version = "0.1.1"
edition = "2021"
description = "A Cargo subcommand for the Axiom Proving API"
authors = ["Axiom Team"]

[dependencies]
clap = { version = "4.4", features = ["derive"] }
dialoguer = "0.10.4"
dirs = "5.0.1"
reqwest = { version = "0.11", features = ["json", "blocking", "multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tar = "0.4"
flate2 = "1.0"
tokio = { version = "1", features = ["full"] }
walkdir = "2.3"
eyre = "0.6.12"
hex = "0.4.3"
cargo-openvm = { git = "https://github.com/openvm-org/openvm.git", default-features = false, tag = "v1.1.2" }
openvm-sdk = { git = "https://github.com/openvm-org/openvm.git", default-features = false, tag = "v1.1.2", features = [
    "evm-verify",
] }
openvm-build = { git = "https://github.com/openvm-org/openvm.git", default-features = false, tag = "v1.1.2" }
comfy-table = "6.1.4"
dotenv = "0.15.0"
