[package]
name = "cargo-axiom"
version = "0.1.1"
description = "A Cargo subcommand for the Axiom Proving API"
authors.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
axiom-sdk = { workspace = true }
cargo-openvm = { workspace = true }

clap = { version = "4.4", features = ["derive"] }
tokio = { version = "1", features = ["full"] }
eyre = "0.6.12"
comfy-table = { version = "6.1.4", default-features = false }
dotenv = "0.15.0"
